// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"uuid"
)

type Sighting struct {
	ID                            uuid.UUID `db:"id" json:"id"`
	CreatedAt                     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt                     time.Time `db:"updated_at" json:"updated_at"`
	GbifKey                       int64     `db:"gbif_key" json:"gbif_key"`
	OccurrenceID                  string    `db:"occurrence_id" json:"occurrence_id"`
	HappenedAt                    time.Time `db:"happened_at" json:"happened_at"`
	BasisOfRecord                 string    `db:"basis_of_record" json:"basis_of_record"`
	RecordedBy                    string    `db:"recorded_by" json:"recorded_by"`
	IndividualCount               *int      `db:"individual_count" json:"individual_count"`
	Remarks                       string    `db:"remarks" json:"remarks"`
	ReferenceUrl                  string    `db:"reference_url" json:"reference_url"`
	Locality                      string    `db:"locality" json:"locality"`
	StateProvince                 string    `db:"state_province" json:"state_province"`
	Country                       string    `db:"country" json:"country"`
	CountryCode                   string    `db:"country_code" json:"country_code"`
	Latitude                      float64   `db:"latitude" json:"latitude"`
	Longitude                     float64   `db:"longitude" json:"longitude"`
	CoordinateUncertaintyInMetres *float64  `db:"coordinate_uncertainty_in_metres" json:"coordinate_uncertainty_in_metres"`
	ElevationInMetres             *float64  `db:"elevation_in_metres" json:"elevation_in_metres"`
	SpeciesID                     uuid.UUID `db:"species_id" json:"species_id"`
	WeatherID                     uuid.UUID `db:"weather_id" json:"weather_id"`
	Media                         string    `db:"media" json:"media"`
}

type Species struct {
	ID             uuid.UUID `db:"id" json:"id"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	GbifKey        int64     `db:"gbif_key" json:"gbif_key"`
	Kingdom        string    `db:"kingdom" json:"kingdom"`
	Phylum         string    `db:"phylum" json:"phylum"`
	Class          string    `db:"class" json:"class"`
	Order          string    `db:"order" json:"order"`
	Family         string    `db:"family" json:"family"`
	Genus          string    `db:"genus" json:"genus"`
	Species        string    `db:"species" json:"species"`
	Rank           string    `db:"rank" json:"rank"`
	ScientificName string    `db:"scientific_name" json:"scientific_name"`
	CanonicalName  string    `db:"canonical_name" json:"canonical_name"`
	VernacularName string    `db:"vernacular_name" json:"vernacular_name"`
}

type Weather struct {
	ID                  uuid.UUID `db:"id" json:"id"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
	ObservedAt          time.Time `db:"observed_at" json:"observed_at"`
	Temperature         float64   `db:"temperature" json:"temperature"`
	ApparentTemperature float64   `db:"apparent_temperature" json:"apparent_temperature"`
	Humidity            int64     `db:"humidity" json:"humidity"`
	Precipitation       float64   `db:"precipitation" json:"precipitation"`
	Rain                float64   `db:"rain" json:"rain"`
	Snowfall            float64   `db:"snowfall" json:"snowfall"`
	CloudCover          int64     `db:"cloud_cover" json:"cloud_cover"`
	WindSpeed           float64   `db:"wind_speed" json:"wind_speed"`
	WindGusts           float64   `db:"wind_gusts" json:"wind_gusts"`
	WindDirection       int64     `db:"wind_direction" json:"wind_direction"`
	ConditionCode       int64     `db:"condition_code" json:"condition_code"`
	Condition           string    `db:"condition" json:"condition"`
}
