// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"uuid"
)

type Querier interface {
	SightingCreate(ctx context.Context, arg SightingCreateParams) (Sighting, error)
	SightingFind(ctx context.Context, id uuid.UUID) (SightingFindRow, error)
	SightingFindByGbifKey(ctx context.Context, gbifKey int64) (SightingFindByGbifKeyRow, error)
	SightingList(ctx context.Context, arg SightingListParams) ([]SightingListRow, error)
	SpeciesCreate(ctx context.Context, arg SpeciesCreateParams) (Species, error)
	SpeciesFind(ctx context.Context, id uuid.UUID) (Species, error)
	SpeciesFindByGbifKey(ctx context.Context, gbifKey int64) (Species, error)
	SpeciesList(ctx context.Context) ([]Species, error)
	WeatherCreate(ctx context.Context, arg WeatherCreateParams) (Weather, error)
	WeatherFind(ctx context.Context, id uuid.UUID) (Weather, error)
}

var _ Querier = (*Queries)(nil)
